---
title: "Data_Analytics_Project"
date: "2022-11-15"
output:
  html_document:
    toc: true
    toc_depth: 2
    number_sections: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Importar les llibreries
library(dplyr)
```

## Getting to know the datasets

```{R}
# Load datasets
DS <- read.csv("cookie_cats_ABtest.csv")
nrow(DS)
ncol(DS)
summary(DS)

```

```{R}
# Load datasets
PR <- read.csv("cookie_cats_purch.csv")
nrow(PR)
ncol(PR)
summary(PR)


```

# 2. Preprocessing
## 2.1 Preprocessing dataset "Cookie Cats AB Testing"

```{R}
unique(DS$version)
unique(DS$sum_gamerounds)
unique(DS$retention_1) #Doing this we can search inconsistencies, like there are FALSE " false" and TRUE " true " variables when it should only be FALSE and TRUE

DS$retention_1[DS$retention_1 == "false "] = FALSE #Changing that "false " into FALSE so we have only one FALSE value
DS$retention_1[DS$retention_1 == "  true "] = TRUE #Changing that " true " into TRUE so we have only one TRUE value

unique(DS$retention_1) #to check if we change the values correctly.
DS$retention_1 = as.logical(DS$retention_1) #now our values in retention_1 are logical values. Before doing that they where strings.
unique(DS$retention_1) #to check if we change the values correctly again.
unique(DS$retention_7) 



```

## 2.2 Preprocessing dataset "Cookie Cats Purchases"

```{R}
#Check the data set for inconsistencies on the values
unique(PR$id)
unique(PR$purch)

#Change all negatives values to positives values
PR$purch <- gsub("-", "", PR$purch)

#Remove all NA values in the dataset
PR <- na.omit(PR)

#Check again to be sure there are no more inconsistencies
unique(PR$id)
unique(PR$purch)

```

# 3. Descriptive analytics
## 3.1 Dataset “Cookie Cats AB Testing”

### 3.1.1 Users that downloaded the game
```{R}
totalUserAmmount <- length(DS$userid)
totalUserAmmount
```

### 3.1.2 Distribution of users in groups
```{R}
#Check the ammount of users for each group of the A/B test
g30_UserAmmount <- length(DS$userid[DS$version == "gate_30"])
g40_UserAmmount <- length(DS$userid[DS$version == "gate_40"])

#Verify that the sum of the ammount of users per group is equal to the totalilty of users
g30_UserAmmount + g40_UserAmmount == totalUserAmmount

g30_Percentile <- (g30_UserAmmount / totalUserAmmount) * 100
g30_Percentile

g40_Percentile <- (g40_UserAmmount / totalUserAmmount) * 100
g40_Percentile

#There's a slightly higher ammount of users in gate40 than in gate30, precisely an 0.87% more
(g40_Percentile - g30_Percentile) 

#We draw a pie chart to see that difference more clearly
pie(c(g30_UserAmmount, g40_UserAmmount),  c("Gate 30", "Gate 40"))


```

### 3.1.3 Game rounds

What is the distribution of game rounds in the players’ population? 

```{R}
boxplot(DS$sum_gamerounds)

```

And among the users of version A and version B of the game separately?

```{R}
boxplot(DS$sum_gamerounds[DS$version == "gate_30"], DS$sum_gamerounds[DS$version == "gate_40"])

```

### 3.1.4 Retention 

What is the value of retention at day 1? (percentage of users that are still active the day after installation).

```{R}
# ---------- RETENTION 1 ----------
#Percentage of users with version gate_30 that are still active the day after installation (among all players with gate_30)
g30Ret1 = length(DS$version[DS$version == "gate_30" & DS$retention_1 == TRUE])
g30Ret1Percentage = (g30Ret1/ g30_UserAmmount) * 100
g30Ret1Percentage

#Percentage of users with version gate_40 that are still active the day after installation (among all players with gate_40)
g40Ret1 = length(DS$version[DS$version == "gate_40" & DS$retention_1 == TRUE])
g40Ret1Percentage = (g40Ret1/ g40_UserAmmount) * 100
g40Ret1Percentage

#There's a slighlty higher retention_1 of users in gate_30 than in gate_40
(g30Ret1Percentage - g40Ret1Percentage)

```

What is the value of retention at day 7? (percentage of users that are still active after one week of installation).

```{R}
# ---------- RETENTION 7 ----------
#Percentage of users with version gate_30 that are still active after one week of installation (among all players with gate_30)
g30Ret7 = length(DS$version[DS$version == "gate_30" & DS$retention_7 == TRUE])
g30Ret7Percentage = (g30Ret7/ g30_UserAmmount) * 100
g30Ret7Percentage

#Percentage of users with version gate_40 that are still active after one week of installation (among all players with gate_40)
g40Ret7 = length(DS$version[DS$version == "gate_40" & DS$retention_7 == TRUE])
g40Ret7Percentage = (g40Ret7/ g40_UserAmmount) * 100
g40Ret7Percentage

#There's a slighlty higher retention_1 of users in gate_30 than in gate_40
(g30Ret7Percentage - g40Ret7Percentage)

```


### 3.1.5 Are there non-playing users?

```{R}
#To know if there are nonplayers, we have to look sum_gamerounds. If they've played  0 rounds, it means they didn't play the game.
#Searching for non players (sum_gamerounds = 0)
nonPlayersAmmount = length(DS$sum_gamerounds[DS$sum_gamerounds == 0])
nonPlayersAmmount

#NonPlayers in percentage
nonPlayersPercentage = (nonPlayersAmmount / totalUserAmmount) * 100
nonPlayersPercentage

#Piechart
names = c("Players", "Non Players")
variables = c(totalUserAmmount, nonPlayersAmmount)

pie(variables, names)
```


## 3.2 Dataset “Cookie Cats Purchases”

# 4. Monetization metrics 

```{R}
#ARPU - Average Revenue Per User 
#Fixing purch to sum up all the purchases. To do that, we split our string purch to use only the numbers and get rid of EUR.
purchFixed = strsplit(PR$purch, split = "EUR")
newPurchFixed = as.vector(unlist(purchFixed))
newPurchFixed = as.numeric(newPurchFixed)

allPurch = sum(newPurchFixed)

#Now we compute our ARPU
arpu = allPurch / totalUserAmmount
arpu

#ARRPU - Average Revenue Per Paying User
#computing the number of players who pay
payingUsers = length(unique(PR$id))
arrpu = allPurch / payingUsers
arrpu

#Conversion Rate
conversionRate = payingUsers/totalUserAmmount
conversionRate

conversionRate * 100
```

# 5. A/B Testing

Research question: Does moving gate to level 40 improve engagement of the users significantly?
```{R}

```

## 5.1. Hypothesis

We'll consider the number of round games of every user. 
Sample A = round games gate 30
Sample B = round games gate 40

Null Hypothesis: Sample B <= Sample A
Alternative Hypothesis: Sample B > Sample A

## 5.2. Visualisation
```{R}
plot(DS[DS$version == "gate_30",]$sum_gamerounds)
plot(DS[DS$version == "gate_40",]$sum_gamerounds)

```
It seems that players in gate 40 plays more game rounds than players in gate 30.

## 5.3. Computation

```{R}
#Confidence level = 95%

#Significance level = 0.05

#mean
meanGameroundsGate30 = mean(DS$sum_gamerounds[DS$version == "gate_30"])
meanGameroundsGate40 = mean(DS$sum_gamerounds[DS$version == "gate_40"])

#sd
sdGate30 = sd(DS$sum_gamerounds[DS$version == "gate_30"])
sdGate40 = sd(DS$sum_gamerounds[DS$version == "gate_40"])

#number of samples
n1 = length(DS$sum_gamerounds[DS$version == "gate_30"])
n2 = length(DS$sum_gamerounds[DS$version == "gate_40"])

#Observed statistic
diffmeans = (meanGameroundsGate40 - meanGameroundsGate30)
squareRoot = sqrt((sdGate30)^2/n1 + (sdGate40)^2/n2)
obsStat =  diffmeans/squareRoot 
obsStat

#degree of freedom (df)
p1 = ((sdGate30)^2/n1 + (sdGate40)^2/n2)^2
p2.1 = (((sdGate30)^2/n1)^2) / (n1 - 1)
p2.2 = (((sdGate40)^2/n2)^2) / (n2 - 1) 

df = p1 / (p2.1 + p2.2)
df

#pvalue
pvalue = pt(obsStat, df, lower.tail = FALSE)
pvalue

#critical value (z)
z = qt(0.05, df, lower.tail = FALSE)
z

```

## 5.4. Conclusion of A/B testing

We can not accept the alternative hypothesis because the observed value (tobs) is smaller than the critical value (z) needed for the acceptance of the alternative hypothesys.

```{R}
obsStat > z
```

This is caused because the difference between the game round mean between gate30 and gate40 is very little so we cannot know if moving from one gate to another will engage people. We will need more samples to prove it.

